from .MaskNodes import NODE_CLASS_MAPPINGS as MASK_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MASK_NODE_DISPLAY_NAME_MAPPINGS
from .SegmentNodes import NODE_CLASS_MAPPINGS as SEGMENT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SEGMENT_NODE_DISPLAY_NAME_MAPPINGS
from .ComposeNodes import NODE_CLASS_MAPPINGS as COMPOSE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMPOSE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**MASK_NODE_CLASS_MAPPINGS, **SEGMENT_NODE_CLASS_MAPPINGS, **COMPOSE_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MASK_NODE_DISPLAY_NAME_MAPPINGS, **SEGMENT_NODE_DISPLAY_NAME_MAPPINGS, **COMPOSE_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']